//******************
//
// scls_math_3d_geometry_core.cpp
//
//******************
// Presentation :
//
// SCLS is a project containing base functions for C++.
// It can also be use in any projects.
//
// The Math "Carl" part represents the mathematical part of SCLS.
// It is named after one one of the greatest mathematician of all times, Carl Freiderich Gauss.
//
// This file contains the source code of scls_math_geometry_core.h.
//
//******************
//
// License (LGPL V3.0) :
//
// Copyright (C) 2024 by Aster System, Inc. <https://aster-system.github.io/aster-system/>
// This file is part of SCLS.
// SCLS is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
// SCLS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with SCLS. If not, see <https://www.gnu.org/licenses/>.
//

// Include the good header file
#include "../scls_math_directory/scls_math_3d_core.h"

// The namespace "scls" is used to simplify the all.
namespace scls {

    // Absolute position handling
    // Returns the absolute X position
    double Transform_Object_3D::absolute_x() const {if(parent() == 0){return a_real_local_parent_x;}return parent()->absolute_x() + a_real_local_parent_x;};
    double Transform_Object_3D::absolute_y() const {if(parent() == 0){return a_real_local_parent_y;}return parent()->absolute_y() + a_real_local_parent_y;};
    double Transform_Object_3D::absolute_z() const {if(parent() == 0){return a_real_local_parent_z;}return parent()->absolute_z() + a_real_local_parent_z;};
    //double Transform_Object_3D::absolute_x() const {if(parent() == 0){return x();}return parent()->absolute_x() + x() * parent()->absolute_scale_x();};
    //double Transform_Object_3D::absolute_y() const {if(parent() == 0){return y();}return parent()->absolute_y() + y() * parent()->absolute_scale_y();};
    //double Transform_Object_3D::absolute_z() const {if(parent() == 0){return z();}return parent()->absolute_z() + z() * parent()->absolute_scale_z();};

    // Extremums
    // TO OPTIMISE
    double Transform_Object_3D::max_absolute_x() const {Point_3D absolute_max = absolute_scale()/2.0;absolute_max.rotate(absolute_rotation());return absolute_x() + absolute_max.x();};
    double Transform_Object_3D::max_absolute_y() const {Point_3D absolute_max = absolute_scale()/2.0;absolute_max.rotate(absolute_rotation());return absolute_y() + absolute_max.y();};
    double Transform_Object_3D::max_absolute_z() const {Point_3D absolute_max = absolute_scale()/2.0;absolute_max.rotate(absolute_rotation());return absolute_z() + absolute_max.z();};
    double Transform_Object_3D::min_absolute_x() const {Point_3D absolute_max = absolute_scale()/2.0;absolute_max.rotate(absolute_rotation());return absolute_x() - absolute_max.x();};
    double Transform_Object_3D::min_absolute_y() const {Point_3D absolute_max = absolute_scale()/2.0;absolute_max.rotate(absolute_rotation());return absolute_y() - absolute_max.y();};
    double Transform_Object_3D::min_absolute_z() const {Point_3D absolute_max = absolute_scale()/2.0;absolute_max.rotate(absolute_rotation());return absolute_z() - absolute_max.z();};

    // Precise next movement
    double Transform_Object_3D::max_absolute_x_next() const {return max_absolute_x() + next_movement_x();};
    double Transform_Object_3D::max_absolute_y_next() const {return max_absolute_y() + next_movement_y();};
    double Transform_Object_3D::max_absolute_z_next() const {return max_absolute_z() + next_movement_z();};
    double Transform_Object_3D::min_absolute_x_next() const {return min_absolute_x() + next_movement_x();};
    double Transform_Object_3D::min_absolute_y_next() const {return min_absolute_y() + next_movement_y();};
    double Transform_Object_3D::min_absolute_z_next() const {return min_absolute_z() + next_movement_z();};
    Point_3D Transform_Object_3D::position_next() const {return Point_3D(x() + next_movement_x(), y() + next_movement_y(), z() + next_movement_z());};

    // Next movement generated by the velocity
    double Transform_Object_3D::next_movement_x()const{return velocity().x() * a_delta_time.to_double();};
    double Transform_Object_3D::next_movement_y()const{return velocity().y() * a_delta_time.to_double();};
    double Transform_Object_3D::next_movement_z()const{return velocity().z() * a_delta_time.to_double();};

    // Next position
    double Transform_Object_3D::x_next() const {return x() + next_movement_x();};
    double Transform_Object_3D::y_next() const {return y() + next_movement_y();};

    // Update the real local position of the children
    void Transform_Object_3D::update_children_real_local_position() {
        for(int i = 0;i<static_cast<int>(children().size());i++){
            Transform_Object_3D* current_child = children()[i].lock().get();
            if(current_child != 0) {current_child->update_real_local_position();}
        }
    };
    // Update the real local position of the object
    void Transform_Object_3D::update_real_local_position() {
        // Calculate the real local parent position
        if(parent() != 0) {
            // Rotate the vector
            double* rotated = __rotate_vector_3d(x() * parent()->absolute_scale_x(), y() * parent()->absolute_scale_y(), z() * parent()->absolute_scale_z(), parent()->absolute_rotation_x(), parent()->absolute_rotation_y(), parent()->absolute_rotation_z());

            // Calculate the final positions
            a_real_local_parent_x = rotated[0];
            a_real_local_parent_y = rotated[1];
            a_real_local_parent_z = rotated[2];
            delete[] rotated; rotated = 0;
        }
        else {
            a_real_local_parent_x = x();
            a_real_local_parent_y = y();
            a_real_local_parent_z = z();
        }

        update_children_real_local_position();
    }

    // Update each vectors
	void Transform_Object_3D::update_vectors() {
		// Update the directions vector
		// Calculate the forward vector
		double* new_forward_vector = __rotate_vector_3d(0, 0, 1, absolute_rotation_x(), absolute_rotation_y(), absolute_rotation_z());
		a_forward_vector_x = new_forward_vector[0]; a_forward_vector_y = new_forward_vector[1]; a_forward_vector_z = new_forward_vector[2];
		// Calculate the right vector
		double* new_right_vector = __rotate_vector_3d(a_forward_vector_x, 0, a_forward_vector_z, 0, -90, 0);
		a_right_vector_x = new_right_vector[0]; a_right_vector_y = new_right_vector[1]; a_right_vector_z = new_right_vector[2];
		// Create the top vector
		double* new_top_vector = __rotate_vector_3d(0, 1, 0, absolute_rotation_x(), absolute_rotation_y(), absolute_rotation_z());
		a_top_vector_x = new_top_vector[0]; a_top_vector_y = new_top_vector[1]; a_top_vector_z = new_top_vector[2];
		// Free the memory
		delete new_forward_vector; new_forward_vector = 0;
		delete new_right_vector; new_right_vector = 0;
		delete new_top_vector; new_top_vector = 0;

		// Update the real position
		update_real_local_position();
		update_rotation();

		// Update children
		for(int i = 0;i<static_cast<int>(children().size());i++) {
			Transform_Object_3D* current_child = children()[i].lock().get();
			if(current_child != 0){current_child->update_vectors();}
		}
	}
}
